import AppKit

/// The SF Symbols a session can get as its icon: built into macOS (nothing bundled). Jev picks in two steps, first a
/// category (from what the session is about), then an icon in it, because it takes at most 255 options per question.
///
/// Hand-picked from Apple's catalogue: one icon per glyph (outlines, no filled, circled or badged variants), none of
/// the symbols Apple restricts to its own products and features, and the older name where Apple renamed a symbol
/// (it works on every macOS; new names don't exist before macOS 15). A few icons only exist on newer macOS and are
/// left out where they can't be drawn. Categories are about what a session is about, not what an icon shows
/// (`hare` is under performance), and stay small: tests check that any two fit in one question.
enum SessionIcons {
    struct Category: Hashable {
        let key: String
        /// What Jev reads when it picks the category.
        let about: String
        let icons: [String]
    }

    static let categories: [Category] = [
        Category(key: "code", about: "Writing code: languages, APIs, refactoring, cleanup, packages, plugins, builds, configuration and developer tools", icons: [
            "terminal", "chevron.left.forwardslash.chevron.right", "curlybraces", "ellipsis.curlybraces", "parentheses",
            "function", "fx", "number", "command", "option", "return", "hammer", "wrench.adjustable", "screwdriver",
            "wrench.and.screwdriver", "gear", "gearshape", "gearshape.2", "slider.horizontal.3", "switch.programmable",
            "puzzlepiece", "puzzlepiece.extension", "cube", "cube.transparent", "shippingbox", "square.stack.3d.up",
            "square.stack", "rectangle.stack", "flowchart", "text.and.command.macwindow", "book.and.wrench",
            "display.and.screwdriver", "folder.badge.gear", "oilcan", "tuningfork", "level", "pencil.and.ruler", "link",
            "trash", "xmark.bin", "scissors", "keyboard.badge.eye", "bolt.horizontal",
        ]),
        Category(key: "debug", about: "Fixing things: bugs, errors, crashes, incidents, tests, investigations and code review", icons: [
            "ladybug", "ant", "microbe", "bandage", "cross.case", "stethoscope", "testtube.2", "fire.extinguisher",
            "light.beacon.max", "sos", "text.magnifyingglass", "doc.text.magnifyingglass",
            "exclamationmark.magnifyingglass", "scope", "dot.scope", "target", "binoculars", "eye", "eyes", "eyeglasses",
            "loupe", "exclamationmark.triangle", "exclamationmark.octagon", "exclamationmark.2",
            "exclamationmark.questionmark", "questionmark", "xmark.octagon", "xmark", "checkmark", "checkmark.diamond",
            "checklist", "checklist.checked", "checklist.unchecked", "pencil.and.list.clipboard", "hand.thumbsup",
            "hand.thumbsdown",
        ]),
        Category(key: "ship", about: "Git and shipping: commits, branches, merges, pull requests, conflicts, versions, releases, deploys, migrations and updates", icons: [
            "arrow.triangle.branch", "arrow.triangle.merge", "arrow.triangle.pull", "arrow.triangle.swap",
            "arrow.uturn.backward", "arrow.uturn.forward", "arrow.counterclockwise", "clock.arrow.circlepath",
            "plus.forwardslash.minus", "tag", "flag", "flag.checkered", "flag.2.crossed", "airplane.departure",
            "shippingbox.and.arrow.backward", "square.and.arrow.up", "square.and.arrow.down", "arrow.down.circle",
            "arrow.up.circle", "arrow.down.circle.dotted", "tray.and.arrow.up", "tray.and.arrow.down", "arrow.up.doc",
            "arrow.down.doc", "signpost.right.and.left", "arrow.rectanglepath", "app.badge", "square.and.arrow.up.on.square",
        ]),
        Category(key: "ui", about: "App interfaces: windows, screens, layouts, menus, navigation, forms, components, input and accessibility", icons: [
            "macwindow", "macwindow.on.rectangle", "macwindow.stack", "macwindow.and.cursorarrow", "uiwindow.split.2x1",
            "sidebar.left", "sidebar.right", "sidebar.squares.left", "menubar.rectangle", "menubar.dock.rectangle",
            "menubar.arrow.down.rectangle", "dock.rectangle", "dock.arrow.up.rectangle", "rectangle",
            "rectangle.on.rectangle", "rectangle.3.group", "rectangle.split.3x1", "rectangle.split.2x2",
            "rectangle.grid.1x2", "square.grid.2x2", "square.grid.3x3", "list.bullet.rectangle",
            "list.bullet.below.rectangle", "list.dash.header.rectangle", "rectangle.and.pencil.and.ellipsis",
            "character.textbox", "button.horizontal", "capsule", "switch.2", "cursorarrow", "cursorarrow.rays",
            "cursorarrow.click", "cursorarrow.motionlines", "contextualmenu.and.cursorarrow", "hand.point.up.left",
            "hand.tap", "keyboard", "keyboard.chevron.compact.down", "computermouse", "arrowkeys", "square.resize",
            "rectangle.expand.vertical", "rectangle.compress.vertical", "aspectratio", "viewfinder", "pip", "ellipsis",
            "line.3.horizontal", "line.3.horizontal.decrease", "app", "qrcode", "figure.roll",
            "rectangle.portrait.and.arrow.right",
        ]),
        Category(key: "design", about: "Visual design: drawing, colour, themes, dark mode, icons, fonts, typography, images, shapes and animation", icons: [
            "paintbrush", "paintbrush.pointed", "paintpalette", "swatchpalette", "eyedropper", "eyedropper.halffull",
            "pencil", "pencil.line", "pencil.and.outline", "pencil.and.scribble", "highlighter", "scribble",
            "scribble.variable", "signature", "lasso", "hand.draw", "eraser", "crop", "crop.rotate", "perspective", "skew",
            "flip.horizontal", "photo", "photo.on.rectangle", "photo.stack", "photo.artframe", "camera.filters",
            "circle.lefthalf.filled", "circle", "square", "triangle", "diamond", "hexagon", "octagon", "pentagon",
            "rhombus", "oval", "seal", "squareshape", "square.on.circle", "circle.hexagongrid", "rays", "textformat",
            "textformat.size", "textformat.abc", "textformat.alt", "bold", "italic", "underline", "strikethrough",
            "character", "character.cursor.ibeam", "paragraph", "fleuron", "f.cursive", "text.alignleft", "lineweight",
            "line.diagonal", "beziercurve", "shadow", "mosaic", "checkerboard.rectangle", "square.3.layers.3d",
            "square.2.layers.3d", "grid", "camera.aperture", "slowmo", "app.translucent",
        ]),
        Category(key: "docs", about: "Docs and files: writing, notes, documents, folders, lists, search, translation, reading and learning", icons: [
            "doc", "doc.text", "doc.plaintext", "doc.richtext", "doc.on.doc", "doc.on.clipboard", "doc.append",
            "doc.questionmark", "doc.text.image", "doc.viewfinder", "doc.zipper", "folder", "folder.badge.person.crop",
            "plus.rectangle.on.folder", "questionmark.folder", "tray", "tray.full", "archivebox", "clipboard",
            "list.bullet", "list.number", "list.dash", "list.star", "list.triangle", "list.bullet.indent", "list.clipboard",
            "list.bullet.clipboard", "note", "note.text", "square.and.pencil", "text.quote", "quote.opening",
            "quote.closing", "text.book.closed", "book", "book.closed", "book.pages", "books.vertical", "bookmark",
            "magazine", "newspaper", "scroll", "menucard", "graduationcap", "studentdesk", "character.book.closed",
            "character.bubble", "text.append", "text.insert", "text.below.photo", "text.viewfinder", "character.magnify",
            "magnifyingglass", "paperclip", "pin",
        ]),
        Category(key: "data", about: "Data: databases, storage, backups, tables, spreadsheets, analytics, charts, statistics, math, sorting and measurement", icons: [
            "cylinder", "cylinder.split.1x2", "externaldrive", "internaldrive", "externaldrive.badge.timemachine",
            "tablecells", "chart.bar", "chart.bar.xaxis", "chart.bar.xaxis.ascending", "chart.bar.doc.horizontal",
            "chart.pie", "chart.line.uptrend.xyaxis", "chart.line.downtrend.xyaxis", "chart.line.flattrend.xyaxis",
            "chart.xyaxis.line", "chart.dots.scatter", "chart.bar.yaxis", "sum", "percent", "plusminus", "divide",
            "multiply", "equal", "greaterthan", "lessthan", "x.squareroot", "pi", "infinity", "angle", "righttriangle",
            "compass.drawing", "ruler", "lines.measurement.horizontal", "scalemass", "barometer", "arrow.up.arrow.down",
            "arrow.left.arrow.right", "point.3.connected.trianglepath.dotted", "circle.grid.cross",
        ]),
        Category(key: "infra", about: "Infrastructure: servers, networks, cloud, internet, APIs over the wire, devices, hardware, power, performance and monitoring", icons: [
            "server.rack", "cloud", "network", "globe", "globe.americas", "globe.europe.africa", "globe.asia.australia",
            "globe.desk", "wifi", "wifi.router", "wifi.exclamationmark", "antenna.radiowaves.left.and.right",
            "dot.radiowaves.left.and.right", "cellularbars", "personalhotspot", "cable.connector", "cable.coaxial",
            "fibrechannel", "powerplug", "powercord", "poweroutlet.strip", "bolt", "battery.100", "batteryblock", "power",
            "togglepower", "restart", "powersleep", "cpu", "memorychip", "sdcard", "simcard", "opticaldiscdrive", "display",
            "display.2", "desktopcomputer", "laptopcomputer", "pc", "smartphone", "tv", "printer", "scanner", "faxmachine",
            "web.camera", "videoprojector", "speedometer", "gauge.with.needle", "waveform.path.ecg", "firewall", "sensor",
            "gyroscope", "fanblades", "hare", "tortoise",
        ]),
        Category(key: "security", about: "Security and accounts: auth, sign-in, passwords, keys, tokens, permissions, privacy, signing and encryption", icons: [
            "lock", "lock.open", "lock.shield", "lock.doc", "lock.rectangle.stack", "key", "key.horizontal",
            "key.2.on.ring", "key.viewfinder", "key.radiowaves.forward", "key.card", "key.shield", "shield",
            "shield.checkered", "checkmark.shield", "exclamationmark.shield", "xmark.shield", "bolt.shield",
            "person.badge.shield.checkmark", "hand.raised", "eye.slash", "exclamationmark.lock", "entry.lever.keypad",
            "hourglass.and.lock", "text.redaction", "checkmark.seal", "xmark.seal", "person.crop.rectangle", "lanyardcard",
            "person.badge.shield.exclamationmark",
        ]),
        Category(key: "ai", about: "AI and ideas: agents, models, prompts, assistants, automation, robots, magic, experiments and science", icons: [
            "sparkles", "sparkle", "sparkles.2", "wand.and.stars", "wand.and.rays", "brain", "brain.head.profile",
            "lightbulb", "lightbulb.2", "atom", "flask", "bubbles.and.sparkles", "sparkle.magnifyingglass",
            "lasso.sparkles", "robotic.vacuum", "bolt.badge.automatic", "gearshape.arrow.triangle.2.circlepath", "drone",
            "person.and.background.dotted", "text.badge.star",
        ]),
        Category(key: "people", about: "People: users, teams, profiles, onboarding, chat, email, calls, notifications, feedback, marketing and social", icons: [
            "person", "person.2", "person.3", "person.crop.circle", "person.crop.square", "person.crop.artframe",
            "person.text.rectangle", "person.bust", "person.wave.2", "person.2.wave.2", "person.line.dotted.person",
            "person.badge.plus", "person.checkmark.and.xmark", "figure.wave", "figure.stand", "figure.child", "hand.wave",
            "hands.clap", "face.smiling", "heart", "star", "bubble", "bubble.left", "bubble.right",
            "bubble.left.and.bubble.right", "ellipsis.bubble", "captions.bubble", "text.bubble", "exclamationmark.bubble",
            "questionmark.bubble", "info.bubble", "plus.bubble", "checkmark.bubble", "quote.bubble", "phone",
            "phone.bubble", "phone.down", "mic", "envelope", "envelope.open", "envelope.badge", "envelope.stack", "mail",
            "paperplane", "megaphone", "bell", "bell.badge", "at", "info",
        ]),
        Category(key: "time", about: "Time and flow: scheduling, calendars, timers, sync, background jobs, queues, retries, loops, status and progress", icons: [
            "clock", "deskclock", "alarm", "timer", "stopwatch", "hourglass", "calendar", "calendar.day.timeline.left",
            "calendar.and.person", "watch.analog", "arrow.clockwise", "arrow.triangle.2.circlepath", "arrow.circlepath",
            "arrow.triangle.capsulepath", "repeat", "repeat.1", "exclamationmark.arrow.circlepath", "play", "pause",
            "playpause", "stop", "forward", "backward", "goforward", "gobackward", "zzz", "timeline.selection",
            "clock.badge", "clock.arrow.2.circlepath",
        ]),
        Category(key: "media", about: "Media and fun: audio, video, music, podcasts, cameras, streaming, games, events, awards and celebrations", icons: [
            "camera", "camera.viewfinder", "camera.macro", "film", "film.stack", "movieclapper", "play.rectangle",
            "play.rectangle.on.rectangle", "tv.and.mediabox", "music.note", "music.note.list", "music.mic",
            "music.quarternote.3", "guitars", "pianokeys", "metronome", "headphones", "speaker", "speaker.wave.2",
            "hifispeaker", "radio", "waveform", "recordingtape", "gamecontroller", "arcade.stick", "dpad", "dice",
            "die.face.5", "suit.spade", "suit.heart", "suit.club", "suit.diamond", "theatermasks", "ticket", "popcorn",
            "party.popper", "balloon", "balloon.2", "fireworks", "gift", "birthday.cake", "trophy", "medal", "crown",
            "rosette", "teddybear",
        ]),
        Category(key: "business", about: "Business and money: payments, checkout, shopping, pricing, invoices, finance, orders, deliveries, jobs and companies", icons: [
            "cart", "bag", "basket", "handbag", "creditcard", "creditcard.and.numbers", "banknote", "dollarsign",
            "eurosign", "sterlingsign", "yensign", "bitcoinsign", "wallet.pass", "wallet.bifold", "purchased", "giftcard",
            "barcode", "receipt", "storefront", "building.2", "building.columns", "briefcase", "case", "box.truck",
        ]),
        Category(key: "places", about: "Places and travel: maps, locations, addresses, routes, transport, trips, buildings, homes and offices", icons: [
            "map", "mappin", "mappin.and.ellipse", "location", "location.north", "signpost.right", "house", "house.lodge",
            "building", "tent", "airplane", "airplane.arrival", "car", "car.2", "bus", "tram", "lightrail", "cablecar",
            "ferry", "car.ferry", "sailboat", "bicycle", "scooter", "motorcycle", "moped", "fuelpump", "ev.charger",
            "suitcase", "suitcase.rolling", "suitcase.cart", "backpack", "figure.walk", "figure.hiking", "beach.umbrella",
            "mountain.2", "stairs", "door.left.hand.open", "sofa", "bed.double", "chair", "lamp.desk",
        ]),
        Category(key: "life", about: "Life and nature: animals, plants, weather, seasons, food, drinks, health, medicine, sport, clothes and everyday objects", icons: [
            "leaf", "tree", "carrot", "fish", "bird", "cat", "dog", "pawprint", "lizard", "fossil.shell", "drop", "flame",
            "snowflake", "sun.max", "moon", "moon.stars", "cloud.sun", "cloud.rain", "cloud.snow", "cloud.bolt",
            "cloud.fog", "wind", "tornado", "hurricane", "rainbow", "sunrise", "sunset", "thermometer", "umbrella",
            "water.waves", "fork.knife", "cup.and.saucer", "mug", "wineglass", "takeoutbag.and.cup.and.straw", "frying.pan",
            "refrigerator", "oven", "pills", "pill", "cross.vial", "syringe", "medical.thermometer", "lungs", "staroflife",
            "allergens", "facemask", "dumbbell", "figure.run", "figure.yoga", "soccerball", "basketball", "tennisball",
            "baseball", "football", "volleyball", "sportscourt", "skateboard", "skis", "surfboard", "tshirt", "shoe",
            "hanger", "washer",
        ]),
    ]

    /// What an icon stands for in a coding session, when its name doesn't say it.
    static let hints: [String: String] = [
        "terminal": "command line, shell, scripts",
        "chevron.left.forwardslash.chevron.right": "source code, HTML, markup",
        "curlybraces": "code, JSON, objects",
        "ellipsis.curlybraces": "code snippets, templates",
        "parentheses": "expressions, Lisp",
        "fx": "formulas, effects",
        "number": "numbers, hashes, IDs",
        "return": "keyboard input, newlines",
        "hammer": "building, compiling",
        "gearshape": "settings, configuration",
        "gearshape.2": "internals, machinery, config",
        "slider.horizontal.3": "settings, tuning, parameters",
        "switch.programmable": "feature flags",
        "puzzlepiece": "plugins, integrations, modules",
        "puzzlepiece.extension": "extensions",
        "cube": "3D, modules, objects",
        "shippingbox": "packages, dependencies, deliveries",
        "square.stack.3d.up": "layers, stacks, architecture",
        "rectangle.stack": "stacks, cards",
        "flowchart": "architecture, workflows, diagrams",
        "text.and.command.macwindow": "CLI apps, command palettes",
        "book.and.wrench": "manuals, maintenance guides",
        "display.and.screwdriver": "device setup, repairs",
        "folder.badge.gear": "project config, dotfiles",
        "oilcan": "maintenance, legacy code",
        "tuningfork": "tuning, calibration",
        "level": "alignment, balance",
        "link": "links, URLs, dependencies",
        "trash": "deleting, cleanup, dead code",
        "xmark.bin": "removing, discarding",
        "scissors": "cutting, trimming",
        "keyboard.badge.eye": "keystrokes, input monitoring",
        "bolt.horizontal": "events, signals",
        "ladybug": "bugs, debugging",
        "ant": "small bugs",
        "microbe": "infections, viruses, hidden bugs",
        "bandage": "patches, hotfixes",
        "cross.case": "first aid, recovery",
        "stethoscope": "diagnostics, health checks",
        "testtube.2": "tests, test suites",
        "fire.extinguisher": "incidents, firefighting",
        "light.beacon.max": "alerts, on-call",
        "sos": "emergencies, help",
        "text.magnifyingglass": "finding text, grep",
        "doc.text.magnifyingglass": "reviewing docs or code",
        "exclamationmark.magnifyingglass": "investigating problems",
        "scope": "precision, targeting",
        "dot.scope": "focus, accuracy",
        "target": "goals, targets",
        "binoculars": "exploring, scouting",
        "eye": "watching, review, visibility",
        "eyes": "looking, vision",
        "eyeglasses": "reading closely, reviewing",
        "loupe": "zoom, inspection",
        "exclamationmark.triangle": "warnings",
        "exclamationmark.octagon": "errors, failures",
        "exclamationmark.2": "urgent",
        "exclamationmark.questionmark": "unexpected behaviour",
        "xmark.octagon": "blocked, stopped",
        "checklist": "tasks, todo lists",
        "pencil.and.list.clipboard": "audits, reviews",
        "hand.thumbsup": "approval, LGTM",
        "hand.thumbsdown": "rejection, feedback",
        "arrow.triangle.branch": "git branches",
        "arrow.triangle.merge": "git merges",
        "arrow.triangle.pull": "pull requests",
        "arrow.triangle.swap": "rebasing, swapping",
        "arrow.uturn.backward": "reverts, undo",
        "arrow.uturn.forward": "redo, reapply",
        "arrow.counterclockwise": "resets, rollbacks",
        "clock.arrow.circlepath": "history, past versions",
        "plus.forwardslash.minus": "diffs, changes",
        "tag": "tags, versions, labels",
        "flag": "milestones, flags",
        "flag.checkered": "finish line, launches",
        "flag.2.crossed": "conflicts",
        "airplane.departure": "deploys, launches",
        "shippingbox.and.arrow.backward": "rollbacks, returns",
        "square.and.arrow.up": "publishing, sharing, exports",
        "square.and.arrow.down": "imports, saving",
        "arrow.down.circle": "downloads, updates",
        "arrow.up.circle": "uploads, upgrades",
        "arrow.down.circle.dotted": "pending downloads",
        "tray.and.arrow.up": "outbox, sending",
        "tray.and.arrow.down": "inbox, receiving",
        "arrow.up.doc": "uploading files",
        "arrow.down.doc": "downloading files",
        "signpost.right.and.left": "decisions, forks in the road",
        "arrow.rectanglepath": "migrations, round trips",
        "app.badge": "app updates, badges",
        "square.and.arrow.up.on.square": "share sheets",
        "rectangle.split.3x1": "columns, split views",
        "list.bullet.rectangle": "list views",
        "rectangle.and.pencil.and.ellipsis": "forms, input fields",
        "capsule": "pills, buttons, tags",
        "switch.2": "toggles, options",
        "cursorarrow.rays": "clicks, interactions",
        "cursorarrow.motionlines": "hover, drag",
        "contextualmenu.and.cursorarrow": "context menus",
        "hand.point.up.left": "pointing, selecting",
        "hand.tap": "touch, taps, gestures",
        "arrowkeys": "keyboard navigation, shortcuts",
        "square.resize": "resizing",
        "aspectratio": "aspect ratio, sizing",
        "viewfinder": "focus, capture area",
        "pip": "picture in picture, overlays",
        "ellipsis": "more menus, overflow",
        "line.3.horizontal": "hamburger menus",
        "line.3.horizontal.decrease": "filters",
        "app": "apps, app icons",
        "qrcode": "QR codes, scanning",
        "figure.roll": "accessibility",
        "rectangle.portrait.and.arrow.right": "logging out, exits",
        "pencil": "editing",
        "scribble": "sketches, handwriting",
        "signature": "signatures, signing",
        "lasso": "selection",
        "eraser": "erasing, clearing",
        "perspective": "transforms, 3D",
        "skew": "distortion, transforms",
        "photo": "images",
        "camera.filters": "filters, blending",
        "circle.lefthalf.filled": "dark mode, contrast, themes",
        "seal": "badges, stickers",
        "rays": "loading, brightness",
        "textformat": "text styling, fonts",
        "fleuron": "ornaments, typography",
        "f.cursive": "fonts, script",
        "lineweight": "stroke width",
        "beziercurve": "vectors, curves, paths",
        "mosaic": "tiles, pixelation",
        "checkerboard.rectangle": "transparency, alpha",
        "square.3.layers.3d": "layers",
        "camera.aperture": "lenses, photography",
        "slowmo": "animation, motion",
        "app.translucent": "glass, translucency, app icons",
        "doc.zipper": "archives, zip files",
        "tray.full": "inboxes, queues",
        "archivebox": "archives, old stuff",
        "square.and.pencil": "composing, writing",
        "scroll": "history, long text",
        "menucard": "menus, specs",
        "graduationcap": "learning, courses, training",
        "studentdesk": "education, school",
        "character.book.closed": "dictionaries, glossaries",
        "character.bubble": "translation, languages, i18n",
        "text.viewfinder": "OCR, text recognition",
        "character.magnify": "find and replace",
        "magnifyingglass": "search",
        "paperclip": "attachments",
        "pin": "pinned items",
        "cylinder": "databases",
        "cylinder.split.1x2": "database shards, partitions",
        "externaldrive": "storage, disks",
        "externaldrive.badge.timemachine": "backups",
        "tablecells": "spreadsheets, tables, grids",
        "chart.bar.doc.horizontal": "reports",
        "chart.dots.scatter": "scatter plots, ML data",
        "sum": "totals, aggregation",
        "infinity": "loops, unlimited",
        "compass.drawing": "geometry",
        "ruler": "measuring, sizes",
        "scalemass": "weights, comparisons",
        "barometer": "pressure, readings",
        "arrow.up.arrow.down": "sorting, ordering",
        "arrow.left.arrow.right": "conversion, mapping, sync both ways",
        "point.3.connected.trianglepath.dotted": "graphs, relations, nodes",
        "circle.grid.cross": "matrices, grids",
        "server.rack": "servers, hosting",
        "cloud": "cloud, hosting",
        "network": "networking, topology",
        "globe": "web, internet, worldwide",
        "globe.desk": "geography, i18n",
        "wifi.exclamationmark": "connection problems, offline",
        "antenna.radiowaves.left.and.right": "broadcast, streaming, wireless",
        "dot.radiowaves.left.and.right": "signals, beacons, webhooks",
        "personalhotspot": "connections, tethering",
        "cable.connector": "connectors, integrations",
        "fibrechannel": "storage networks",
        "powerplug": "plugging in, integrations",
        "bolt": "power, speed, energy",
        "batteryblock": "energy, batteries",
        "power": "on/off, startup",
        "restart": "restarts, reboots",
        "powersleep": "sleep, idle",
        "cpu": "processors, compute",
        "memorychip": "memory, RAM",
        "sdcard": "storage cards",
        "display.2": "multiple screens",
        "pc": "Windows, PCs",
        "smartphone": "mobile, phones",
        "speedometer": "performance, speed",
        "gauge.with.needle": "metrics, levels",
        "waveform.path.ecg": "monitoring, health checks, vitals",
        "firewall": "firewalls, network rules",
        "sensor": "sensors, IoT",
        "gyroscope": "motion, orientation",
        "fanblades": "cooling, thermals",
        "hare": "fast, speed-ups, performance",
        "tortoise": "slow, latency",
        "lock": "locking, security",
        "lock.open": "unlocking, access",
        "lock.doc": "encrypted files",
        "key": "keys, passwords, API keys",
        "key.horizontal": "keys, credentials",
        "key.2.on.ring": "keychain, secrets",
        "key.viewfinder": "passkeys",
        "key.radiowaves.forward": "remote unlock, tokens",
        "key.card": "access cards, tokens",
        "key.shield": "secure keys",
        "shield": "protection",
        "shield.checkered": "protection, sandboxing",
        "person.badge.shield.checkmark": "verified users",
        "hand.raised": "permissions, privacy, stop",
        "eye.slash": "hidden, private",
        "entry.lever.keypad": "PIN codes, access",
        "hourglass.and.lock": "rate limits, session timeouts",
        "text.redaction": "redaction, masking secrets",
        "checkmark.seal": "verified, certificates, code signing",
        "xmark.seal": "invalid certificates",
        "person.crop.rectangle": "identity, ID cards",
        "lanyardcard": "badges, identity",
        "sparkles": "AI, magic, new",
        "sparkle": "highlights, AI",
        "wand.and.stars": "magic, auto-fix, generation",
        "wand.and.rays": "auto-enhance",
        "brain": "AI, models, thinking",
        "brain.head.profile": "minds, cognition, memory",
        "lightbulb": "ideas, tips",
        "atom": "science, physics, React",
        "flask": "experiments, prototypes",
        "bubbles.and.sparkles": "clean-ups, polish",
        "sparkle.magnifyingglass": "AI search",
        "lasso.sparkles": "smart selection",
        "robotic.vacuum": "robots, bots, automation",
        "bolt.badge.automatic": "automation",
        "gearshape.arrow.triangle.2.circlepath": "automation, pipelines",
        "drone": "drones, robots",
        "person.and.background.dotted": "agents, personas",
        "text.badge.star": "prompts, featured text",
        "person.crop.circle": "profiles, accounts",
        "person.text.rectangle": "contacts, user cards",
        "person.bust": "avatars",
        "person.wave.2": "presence, speaking",
        "person.line.dotted.person": "pairing, handoff",
        "person.badge.plus": "sign-up, invites",
        "person.checkmark.and.xmark": "user review, moderation",
        "figure.child": "family, kids",
        "hand.wave": "welcome, onboarding",
        "hands.clap": "celebration, applause",
        "heart": "likes, favourites, love",
        "star": "favourites, ratings",
        "ellipsis.bubble": "typing, chat",
        "captions.bubble": "captions, subtitles",
        "questionmark.bubble": "help, FAQ, support",
        "paperplane": "sending, messaging",
        "megaphone": "announcements, marketing",
        "bell": "notifications",
        "bell.badge": "unread notifications",
        "at": "mentions, handles, email",
        "info": "information, about",
        "deskclock": "clocks, time",
        "alarm": "alarms, reminders",
        "calendar.day.timeline.left": "agendas, timelines",
        "calendar.and.person": "meetings, bookings",
        "arrow.clockwise": "refresh, reload",
        "arrow.triangle.2.circlepath": "sync",
        "arrow.circlepath": "retry, redo",
        "arrow.triangle.capsulepath": "loops, pipelines",
        "repeat": "recurring, repeating",
        "exclamationmark.arrow.circlepath": "failed retries",
        "play": "start, run",
        "pause": "pause, suspend",
        "stop": "stop, cancel",
        "zzz": "idle, sleeping, cron",
        "timeline.selection": "timelines, ranges",
        "clock.badge": "scheduled, pending",
        "clock.arrow.2.circlepath": "periodic jobs",
        "play.rectangle": "video players",
        "tv.and.mediabox": "streaming, TV",
        "music.mic": "karaoke, vocals",
        "metronome": "rhythm, tempo",
        "waveform": "audio, sound, voice",
        "recordingtape": "recordings, voicemail",
        "dice": "randomness, games of chance",
        "theatermasks": "drama, roleplay, personas",
        "party.popper": "celebration, launch party",
        "gift": "gifts, rewards",
        "trophy": "wins, achievements",
        "crown": "top, premium, admin",
        "rosette": "awards, badges",
        "bag": "shopping",
        "basket": "basket, groceries",
        "creditcard": "payments, cards",
        "banknote": "cash, money",
        "wallet.pass": "passes, tickets, wallets",
        "purchased": "purchases, orders",
        "barcode": "products, inventory",
        "receipt": "receipts, invoices",
        "storefront": "stores, shops",
        "building.2": "companies, offices",
        "building.columns": "banks, government, institutions",
        "briefcase": "work, jobs",
        "case": "cases, projects",
        "box.truck": "delivery, logistics",
        "location.north": "navigation, compass",
        "signpost.right": "directions, routes",
        "house": "home, homepage",
        "building": "buildings",
        "ev.charger": "EV charging",
        "door.left.hand.open": "entrances, exits",
        "lamp.desk": "desks, offices",
        "leaf": "nature, green, eco",
        "drop": "water, liquids",
        "flame": "fire, hot, trending",
        "snowflake": "cold, frozen",
        "rainbow": "colour, diversity",
        "fork.knife": "food, restaurants",
        "takeoutbag.and.cup.and.straw": "takeaway, food delivery",
        "pills": "medicine, health",
        "cross.vial": "lab tests, blood",
        "syringe": "injection, vaccines",
        "staroflife": "medical, emergencies",
        "dumbbell": "fitness, gym",
        "hanger": "clothes, wardrobe",
        "washer": "laundry",
    ]

    /// Jev's limit on options per question.
    static let maxOptions = 255

    /// The icons this Mac can draw.
    static let drawable: Set<String> = Set(categories.flatMap(\.icons).filter {
        NSImage(systemSymbolName: $0, accessibilityDescription: nil) != nil
    })

    /// The categories that still have icons to offer, with those icons: drawable here and not in `excluded` (icons
    /// already on screen, or rejected for this session).
    static func open(excluding excluded: Set<String>) -> [(category: Category, icons: [String])] {
        categories.compactMap { category in
            let icons = category.icons.filter { drawable.contains($0) && !excluded.contains($0) }
            return icons.isEmpty ? nil : (category, icons)
        }
    }

    /// The icons to offer once Jev has scored the open categories: the best one's, plus the runner-up's when Jev was
    /// torn between them (at least half as likely) and both fit in one question.
    static func shortlist(_ open: [(category: Category, icons: [String])], probabilities: [String: Double]) -> [String] {
        let ranked = open.sorted { probabilities[$0.category.key, default: 0] > probabilities[$1.category.key, default: 0] }
        guard let best = ranked.first else { return [] }
        var icons = best.icons
        if ranked.count > 1 {
            let second = ranked[1]
            if probabilities[second.category.key, default: 0] >= probabilities[best.category.key, default: 0] / 2,
               icons.count + second.icons.count <= maxOptions {
                icons += second.icons
            }
        }
        return Array(icons.prefix(maxOptions))
    }
}
